# Generated by Django 5.0.6 on 2024-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_alter_registro_fecha_registro2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='registro2',
        ),
    ]
