# Generated by Django 5.1 on 2024-08-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_delete_project_alter_planta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='r_ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativa', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.planta')),
            ],
        ),
    ]
