# Generated by Django 5.0.6 on 2024-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_registro_relativa_registro_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='relativa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='r_ambiente',
        ),
    ]
